insert into permission_catalog (key, description) values
  ('billing.edit', 'Edit pricing and billing settings'),
  ('staff.manage', 'Manage staff roles and permissions'),
  ('scheduling.manage', 'Manage bookings and resources'),
  ('catalog.manage', 'Manage catalog items'),
  ('forms.manage', 'Manage form templates and view submissions'),
  ('payments.manage', 'View transactions and issue refunds'),
  ('crm.manage', 'Manage leads and assignments'),
  ('portal.manage', 'Manage customer portal access'),
  ('documents.manage', 'Manage documents and signatures'),
  ('notifications.manage', 'Manage notification templates'),
  ('reviews.manage', 'Moderate reviews'),
  ('search.manage', 'Manage search projections and saved search policy'),
  ('loyalty.manage', 'Manage loyalty rules and accounts'),
  ('calculators.manage', 'Manage calculator configs'),
  ('media.manage', 'Manage media library'),
  ('content.manage', 'Manage pages, blog, SEO, localization, and publishing'),
  ('commerce.manage', 'Manage carts, orders, inventory, fulfillment, and returns'),
  ('memberships.manage', 'Manage customer plans, enrollments, attendance, and progress'),
  ('workflows.manage', 'Manage cases, tickets, claims, projects, and assignments'),
  ('learning.manage', 'Manage courses, assessments, grades, and certificates'),
  ('analytics.read', 'View tenant business analytics and reports'),
  ('locations.manage', 'Manage branches, service areas, and delivery zones'),
  ('communications.manage', 'Manage customer conversations and chat channels');
