insert into features (key, description) values
  ('scheduling', 'Availability, bookings, reservations, classes, and waitlists'),
  ('catalog', 'Listings, products, services, profiles, categories, and variants'),
  ('forms', 'Forms and intake'),
  ('payments', 'Tenant customer payments, deposits, refunds, and donations'),
  ('crm', 'CRM and leads'),
  ('portal', 'Client portal'),
  ('documents', 'Documents and e-signature'),
  ('notifications', 'Outbound email, SMS, push, and reminders'),
  ('reviews', 'Reviews and testimonials'),
  ('search', 'Search and comparison'),
  ('loyalty', 'Points, tiers, rewards, vouchers, and referrals'),
  ('calculators', 'Calculators'),
  ('media', 'Media, galleries, proofing, and private delivery'),
  ('content', 'Pages, blog, SEO, localization, navigation, and publishing'),
  ('commerce', 'Cart, orders, inventory, fulfillment, returns, and gift cards'),
  ('memberships', 'Customer plans, enrollments, attendance, and progress'),
  ('workflows', 'Cases, tickets, claims, projects, checklists, and timelines'),
  ('learning', 'Courses, assessments, grades, progress, and certificates'),
  ('analytics', 'Tenant business dashboards, metrics, and reports'),
  ('locations', 'Branches, service areas, delivery zones, and map data'),
  ('communications', 'Two-way chat, WhatsApp conversations, and message history');
